DROP TABLE IF EXISTS REGION_VEHICLE;
DROP TABLE IF EXISTS ROUTE_STOP;
DROP TABLE IF EXISTS TRIP;
DROP TABLE IF EXISTS STOP;
DROP TABLE IF EXISTS SITE;
DROP TABLE IF EXISTS ROUTE;
DROP TABLE IF EXISTS REGION;
DROP TABLE IF EXISTS VEHICLE;